name: lapang_bola_flutter
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  json_annotation: ^2.0.0
  flutter:
    sdk: flutter
  file_picker: ^1.2.0
  carousel_pro: ^0.0.13
  flutter_verification_code_input:
    git:
      url: git://github.com/tinylife-io/flutter_verification_code_input.git
  universal_html: ^1.1.4
  dropdownfield: 1.0.0
  image_picker: ^0.6.0+9
  smooth_star_rating : 1.0.3
  fancy_bottom_navigation: ^0.1.0
  curved_navigation_bar: ^0.3.1
  carousel_slider: ^1.3.0
  intl: ^0.16.0
  indonesia: ^1.0.1
  progress_dialog: ^1.2.0
  http: ^0.12.0+2
  flutter_share_me: ^0.1.3
  screenshot: ^0.1.1
  image_gallery_saver: '^1.2.2'
  image_picker_saver: ^0.3.0
  share: ^0.6.2+3
  path_provider: ^1.5.1
  flutter_share_file: ^1.1.4+1
  esys_flutter_share: ^1.0.2



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/Dashboard.png
    - assets/Grafis_profile.png
    - assets/tombol_slider_kanan.png
    - assets/tombol_slider_kiri.png
    - assets/Kalender.png
    - assets/Logo.png
    - assets/Lokasi.png
    - assets/My_match.png
    - assets/Setting.png
    - assets/Lupa_password.png
    - assets/Sign_in.png
    - assets/Attack.png
    - assets/Teamwork.png
    - assets/Verifikasi.png
    - assets/Register.png
    - assets/Hide.png
    - assets/User.png
    - assets/Camera.png
    - assets/Drive.png
    - assets/File_manager.png
    - assets/Files.png
    - assets/Gallery.png
    - assets/Photo.png
    - assets/Profile_pict.png
    - assets/Share_me.png
    - assets/WA.png
    - assets/Lapangbola_share.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family : Avenir
      fonts:
        - asset : assets/Avenir.ttc
    - family : Avenir_bold
      fonts:
        - asset: assets/Avenir-bold.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
